## <font size = "8"><b>_Array_<b>

In [3]:
import numpy as np


a = np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


## Restrictions of Numpy Array
- All the elements of the array must be same type of data.
- Once created, the total size of the array can't change.

In [2]:
new_array = np.array([23,45,78])
print(new_array)

[23 45 78]


In [3]:
new_array_1 =  np.array([12,23,"Budhist records of the western world"])
print(new_array_1)

['12' '23' 'Budhist records of the western world']


In [4]:
new_array_1

array(['12', '23', 'Budhist records of the western world'], dtype='<U36')

In [5]:
a

array([1, 2, 3, 4, 5, 6])

In [6]:
new_array

array([23, 45, 78])

In [10]:
import numpy as n

a = n.array([34,23,2])
print(a)
print(type(a))

[34 23  2]
<class 'numpy.ndarray'>


In [8]:
import numpy as ab


a = ab.array({1,2,3,4,5,60})
print(a)
a

{1, 2, 3, 4, 5, 60}


array({1, 2, 3, 4, 5, 60}, dtype=object)

In [31]:
import numpy as np


a = np.array((1,2,3,4,5,"60","pankaj"))
print(a)
a

['1' '2' '3' '4' '5' '60' 'pankaj']


array(['1', '2', '3', '4', '5', '60', 'pankaj'], dtype='<U21')

In [1]:
import numpy as np


a = np.array([1,2,3,4,5,60,90.01])
print(a)
a

[ 1.    2.    3.    4.    5.   60.   90.01]


array([ 1.  ,  2.  ,  3.  ,  4.  ,  5.  , 60.  , 90.01])

In [24]:
array2 = np.array([12,23,"If the Plan dosen't work change the plan but never the goal",
                  "Budhist Records of the Western world"])
array2

array(['12', '23',
       "If the Plan dosen't work change the plan but never the goal",
       'Budhist Records of the Western world'], dtype='<U59')

In [22]:
new_array_1 = np.array([12,23,"Budhist Records of the western world"])
new_array_1

array(['12', '23', 'Budhist Records of the western world'], dtype='<U36')

***We can access an individual element of this array as we would access an element in the original int using intger index of the element within the square brackets.***

In [37]:
new_array_1[2]

np.str_('Budhist Records of the western world')

In [38]:
array2[2]

np.str_("If the Plan dosen't work change the plan but never the goal")

In [41]:
array2[0]

np.str_('12')

***Another differenece between an array and a list of lists is that an element of the array can be accessed by specifying the index along each axis within a single set of square bracket seperate by comma.***

In [3]:
t_die_array = np.array([[1,2,3,4],[5,6,7,8],[8,9,0,2],[1,22,3,3]])
print(t_die_array)
t_die_array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 8  9  0  2]
 [ 1 22  3  3]]


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 8,  9,  0,  2],
       [ 1, 22,  3,  3]])

In [13]:
t_die_array[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
two_die_array = np.array([[1,2,3],[5,6,7,],[8,9,0]])
print(two_die_array)
two_die_array

[[1 2 3]
 [5 6 7]
 [8 9 0]]


array([[1, 2, 3],
       [5, 6, 7],
       [8, 9, 0]])

In [14]:
two_die_array[:,2]

array([3, 7, 0])

In [16]:
two_die_array[:,2]

array([3, 7, 0])

<font size = "5">***Array Attributes***

***ndim:*** The number of dimensions of an array is contained in the ndim attribute.

In [49]:
zero_dim_array = np.array(34)
zero_dim_array.ndim

0

In [41]:
zero_dim_array = np.array(34)
zero_dim_array.ndim

0

In [46]:
one_dim_array = np.array([1,2,3,4])
one_dim_array.ndim

1

In [2]:
two_dim_array = np.array([[2,3],[4,5]])
two_dim_array.ndim

NameError: name 'np' is not defined

***shape:*** The shape of an array ia a tuple of non-negative integers that quickly the number of elements along each dimensions.

In [48]:
x = np.array([[1,2,3],[4,5,6]])
print(x)
print(x.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


***size:*** The fixed, total number of elements in array is contained in the size attributes.

In [50]:
table_of_2 = np.array([[2,4,6,8,10],[1,3,5,7,9]])
print(table_of_2.size)
print(table_of_2.shape)

10
(2, 5)


***dtype:*** The data type of the elements if the array can be checked using the dtype attributes.

***Note:*** The data type of all the elements of a numpy array is same. i,e. Homegenous

In [52]:
table_of_2.dtype

dtype('int64')

In [53]:
x.dtype

dtype('int64')

In [54]:
x.ndim

2

In [61]:
x.size

6

In [62]:
x.shape

(2, 3)

In [56]:
x[0,]

array([1, 2, 3])

In [57]:
x[:,0]

array([1, 4])

In [63]:
x[1,2]

np.int64(6)

In [17]:
x.itemsize

8

In [18]:
x.size

4

## Same Order Techniques to create an array
- The section covers np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace()

***np.zeros()*** You can create an array filled with zeros.

In [65]:
zero_array = np.zeros(6)
print(zero_array)
print(type(zero_array))
print(zero_array.shape)
print(zero_array.size)

[0. 0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>
(6,)
6


In [69]:
# Create a table of zero (2 rows 3 column)

zero_array_table = np.zeros((2,3))
print(zero_array_table)

[[0. 0. 0.]
 [0. 0. 0.]]


***np.ones()*** You can create an array filled with ones.

In [70]:
ones_array = np.ones(4)
print(ones_array)

[1. 1. 1. 1.]


In [74]:
ones_array_2d = np.ones((5,2))
print(ones_array_2d)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


***np.empty()*** This creates an empty array. The elements of an array are randoms and depends on the state of the memory. The reason is an empty over zeros is speed - just make sure to fill every elments afterwards.

In [2]:
empty_array = np.empty(6)
empty_array

array([2.22522597e-306, 3.11510340e-307, 3.11521375e-307, 2.22520967e-307,
       1.61323372e-307, 4.67296746e-307])

***np.arange(start, stop, step)*** Create an array within a range.

In [7]:
x = np.arange(4)
x

array([0, 1, 2, 3])

In [5]:
x = np.arange(5,12,2)
x

array([ 5,  7,  9, 11])

***np.linspace(start, stop, step)*** Creates an array with values that are space lineraly in specific integral.

In [11]:
new_array = np.linspace(4,19,20)
new_array

array([ 4.        ,  4.78947368,  5.57894737,  6.36842105,  7.15789474,
        7.94736842,  8.73684211,  9.52631579, 10.31578947, 11.10526316,
       11.89473684, 12.68421053, 13.47368421, 14.26315789, 15.05263158,
       15.84210526, 16.63157895, 17.42105263, 18.21052632, 19.        ])

In [12]:
n_array = np.linspace(1,2,100)
n_array

array([1.        , 1.01010101, 1.02020202, 1.03030303, 1.04040404,
       1.05050505, 1.06060606, 1.07070707, 1.08080808, 1.09090909,
       1.1010101 , 1.11111111, 1.12121212, 1.13131313, 1.14141414,
       1.15151515, 1.16161616, 1.17171717, 1.18181818, 1.19191919,
       1.2020202 , 1.21212121, 1.22222222, 1.23232323, 1.24242424,
       1.25252525, 1.26262626, 1.27272727, 1.28282828, 1.29292929,
       1.3030303 , 1.31313131, 1.32323232, 1.33333333, 1.34343434,
       1.35353535, 1.36363636, 1.37373737, 1.38383838, 1.39393939,
       1.4040404 , 1.41414141, 1.42424242, 1.43434343, 1.44444444,
       1.45454545, 1.46464646, 1.47474747, 1.48484848, 1.49494949,
       1.50505051, 1.51515152, 1.52525253, 1.53535354, 1.54545455,
       1.55555556, 1.56565657, 1.57575758, 1.58585859, 1.5959596 ,
       1.60606061, 1.61616162, 1.62626263, 1.63636364, 1.64646465,
       1.65656566, 1.66666667, 1.67676768, 1.68686869, 1.6969697 ,
       1.70707071, 1.71717172, 1.72727273, 1.73737374, 1.74747

***Concatenation & Sorting of Arrays***

The sections covers np.sort(), np.concatnate()

***np.sort()***

In [3]:
array1 = np.array([10,2,3,4,5])
new_array1 = np.sort(array1)
new_array1

array([ 2,  3,  4,  5, 10])

In [47]:
array1

array([10,  2,  3,  4,  5])

In [4]:
print(new_array1)

[ 2  3  4  5 10]


In [62]:
a = np.sort([1, 24,  3,  4,  5, 10])
a

array([ 1,  3,  4,  5, 10, 24])

***np.conatenate()***

In [7]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
a1 + a2

array([5, 7, 9])

In [8]:
print(a1 + a2)

[5 7 9]


In [21]:
# Concatenation

concatenated_array = np.concatenate((a1,a2))
concatenated_array

array([1, 2, 3, 4, 5, 6])

In [22]:
concatenated_array = np.concatenate((a2,a1))
concatenated_array

array([4, 5, 6, 1, 2, 3])

In [20]:
# Concatenate 2d arrays

a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print("x \n",a)
print("y \n",b)

x 
 [[1 2]
 [3 4]]
y 
 [[5 6]
 [7 8]]


In [28]:
# Concatenate along  axis = 0

np.concatenate((a,b) , axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [25]:
# Concatenate along axis = 1

np.concatenate((a,b) , axis = 1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
Axis = 0 direction (down/row)

|
|
|
|
|
|
↓


Axis = 1 direction (across/column)

----------------→

 ***arr.reshape()***  Using arr.reshape() will give here shape to an array without changing the data. Just remember that when you use the reshape method, the array you want to produce needs to have the same number of elements as the original array. If you start an array with 12 elements you'll need to make sure that your new array also have a total of 12 elements.

In [1]:
import numpy as np

In [30]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [31]:
a.shape

(6,)

In [33]:
b = a.reshape(3,2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [34]:
a

array([0, 1, 2, 3, 4, 5])

In [35]:
c = b.reshape(4,1)
c

ValueError: cannot reshape array of size 6 into shape (4,1)

In [36]:
d = b.reshape(6,1)
d

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [38]:
e = b.reshape(1,6)
e

array([[0, 1, 2, 3, 4, 5]])

***Indexing Using Conditions of Arrays***

In [64]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [51]:
a<5 # boolean array

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [52]:
print(a[a<5]) # give elements

[1 2 3 4]


In [55]:
# You can select even numbers

print(a[a % 2 == 0])

[ 2  4  6  8 10 12]


In [ ]:
c = a

In [2]:
# You cannot use and we can use &

c = a[(a > 2) & (a < 12)]
c

NameError: name 'a' is not defined

In [68]:
# You cannot use orn we can use |

c = a[(a > 2) | (a < 11)]
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

***Basic Array Operations***

The section covers addition , subtraction , multiplication , division and more.

In [4]:
# You can add arrays together with the + sign

data = np.array([1,2,3])
data1 = np.array([4,5,6])
data + data1

array([5, 7, 9])

In [5]:
# Subtraction
print(data - data1)
# multiplication
print(data * data1)
# division
print(data / data1)

[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


***arr.sum():*** Sums all the elements in an array.

In [6]:
a = np.array([1,2,3,4])
a.sum()

np.int64(10)

In [11]:
b = np.array([[1,2,3],
             [4,5,6]])
b.sum(axis = 0)

array([5, 7, 9])

In [10]:
b = np.array([[9,8,7],
             [6,5,4]])
b.sum(axis = 1)

array([24, 15])

## Broadcasting
- Broadcasting is a mechanism that allows Numpy to perform operations on arrays of different shapes.
- There are many broadcasting rules, which you can learn form the numpy documentation.

In [4]:
distance_in_km = np.array([5,2,7,3]) # shape : (4,) Dimension : 1
single_value = np.array(1000) # shape : () Dimension : 0
distance_in_km * single_value

array([5000, 2000, 7000, 3000])

In [17]:
print(distance_in_km.shape)
print(single_value.shape)

(4,)
()


In [18]:
print(distance_in_km.ndim)
print(single_value.ndim)

1
0


In [5]:
distance_in_km / single_value

array([0.005, 0.002, 0.007, 0.003])

In [7]:
distance_in_km + single_value

array([1005, 1002, 1007, 1003])

In [8]:
distance_in_km - single_value

array([-995, -998, -993, -997])

In [9]:
single_value - distance_in_km

array([995, 998, 993, 997])