- To create an array: ***np.array([elements])***
- To access an individual elemnet: ***array[index_value]***
- To find numbers of dimensions: ***array.ndim***
- To find the shape of an array: ***array.shape***
- To find the size of an array: ***array.size***
- To find the data type of an element: ***array.dtype***


<Font size = '5'>***We can create an array by some others methods-***

- By zeros method: ***np.zeros()***
- By ones method: ***np.ones()***
- By empty method: ***np.empty***
- By arange(start, stop, step): ***np.arange(start, stop, step)***
- By linspace(start, stop, step): ***np.linspace(start, stop, step)***

- Sorting: ***np.sort()***
- Concatenation: ***np.concatenate((array1, array2))***
- To add two array horizontally we use ***np.concatenate((array1 , array2), axis = 0)***
- To add two array vertically we use ***np.concatenate((array1 , array2), axis = 1)***

- To shape array without changing data of array: ***array.reshape()***


***Indexing using conditiions of Array***
- a[condition]

***Basic operatioins of Array***
- Sum +
- Subtraction -
- Multiplication *
- Division /

- To add all the elements of the array: ***array.sum()***

<font size = '5'> ****Broadcasting****
- To perform basic operation between two different dimensions arrays.

In [2]:
import numpy as np

In [4]:
a = np.array(["Panakj",34,9,1.05,"numpy"])
print(a)

['Panakj' '34' '9' '1.05' 'numpy']


In [6]:
print(type(a))

<class 'numpy.ndarray'>


In [7]:
b = np.array([1,2,3,4,5.0])
print(b)

[1. 2. 3. 4. 5.]


In [8]:
c = np.array([23,45,12])
print(c)

[23 45 12]


In [9]:
c

array([23, 45, 12])

In [14]:
a = np.array((34,2,23))
print(type(a))
print(a)

<class 'numpy.ndarray'>
[34  2 23]


In [16]:
a[1]

np.int64(2)

In [19]:
x = np.array([["Pankaj",23,100,"A"],["Raja",34,90,"B"],["Rohit",45,99,"B"],["Rohit",55,89,"C"]])
print(x)

[['Pankaj' '23' '100' 'A']
 ['Raja' '34' '90' 'B']
 ['Rohit' '45' '99' 'B']
 ['Rohit' '55' '89' 'C']]


In [7]:
y = np.array([['12',2,3,12],[12,5,6,92],[12,2,3,12],[12,56,9,2]])
print(y)

[['12' '2' '3' '12']
 ['12' '5' '6' '92']
 ['12' '2' '3' '12']
 ['12' '56' '9' '2']]


In [30]:
print(x + y)

[['Pankaj12' '232' '1003' 'A12']
 ['Raja12' '345' '906' 'B92']
 ['Rohit12' '452' '993' 'B12']
 ['Rohit12' '5556' '899' 'C2']]


In [35]:
a = np.concatenate((x ,y))
a

array([['Pankaj', '23', '100', 'A'],
       ['Raja', '34', '90', 'B'],
       ['Rohit', '45', '99', 'B'],
       ['Rohit', '55', '89', 'C'],
       ['12', '2', '3', '12'],
       ['12', '5', '6', '92'],
       ['12', '2', '3', '12'],
       ['12', '56', '9', '2']], dtype='<U21')

In [37]:
a = np.concatenate((x ,y), axis = 1)
a

array([['Pankaj', '23', '100', 'A', '12', '2', '3', '12'],
       ['Raja', '34', '90', 'B', '12', '5', '6', '92'],
       ['Rohit', '45', '99', 'B', '12', '2', '3', '12'],
       ['Rohit', '55', '89', 'C', '12', '56', '9', '2']], dtype='<U21')

In [38]:
x

array([['Pankaj', '23', '100', 'A'],
       ['Raja', '34', '90', 'B'],
       ['Rohit', '45', '99', 'B'],
       ['Rohit', '55', '89', 'C']], dtype='<U21')

In [41]:
x[:,0]

array(['Pankaj', 'Raja', 'Rohit', 'Rohit'], dtype='<U21')

In [43]:
x[:,3]

array(['A', 'B', 'B', 'C'], dtype='<U21')

In [4]:
x[0]

array(['Pankaj', '23', '100', 'A'], dtype='<U21')

In [27]:
x

array([['Pankaj', '23', '100', 'A'],
       ['Raja', '34', '90', 'B'],
       ['Rohit', '45', '99', 'B'],
       ['Rohit', '55', '89', 'C']], dtype='<U21')

In [8]:
y

array([['12', '2', '3', '12'],
       ['12', '5', '6', '92'],
       ['12', '2', '3', '12'],
       ['12', '56', '9', '2']], dtype='<U21')

In [18]:
print(y[1:1])

[]


In [15]:
y[2,1]

np.str_('2')

In [22]:
a = x[x[:,1]]

IndexError: arrays used as indices must be of integer (or boolean) type

In [23]:
import numpy as np
x = np.array([["Pankaj",23,100,"A"],
              ["Raja",34,90,"B"],
              ["Rohit",45,99,"B"],
              ["Rohit",55,89,"C"]])

row = x[x[:,0] == "Pankaj"]
print(row)


[['Pankaj' '23' '100' 'A']]


In [26]:
print(x[0,0])

Pankaj


In [29]:
print(x[3,3])

C


In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('titanic.csv')

In [3]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [4]:
df.head(5).tail(1)

PassengerId  Survived  Pclass                      Name   Sex   Age  SibSp  \
4            5         0       3  Allen, Mr. William Henry  male  35.0      0   

   Parch  Ticket  Fare Cabin Embarked  
4      0  373450  8.05   NaN        S

In [9]:
df.shape

(891, 12)

In [11]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [13]:
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...                        
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [1]:
import numpy as np

In [2]:
new_array = np.array([12,3,4,"pankaj",'data',20.00])

In [4]:
print(new_array)

['12' '3' '4' 'pankaj' 'data' '20.0']


In [5]:
new_array.shape

(6,)

In [6]:
new_array.size

6

In [7]:
new_array[0]

np.str_('12')

In [8]:
print(new_array[1])

3


In [9]:
t = np.array([[12,34,23],[23,2,3],[37,23,32]])

In [27]:
print(t)
print(t.ndim)
print(t.shape)
print(t.size)
print(t.dtype)
print(t[1,1])
print(t[0,])
print(t[:,0])
print(t[:,1])
print(t[1,])
print(t.itemsize)
print(t.size)

[[12 34 23]
 [23  2  3]
 [37 23 32]]
2
(3, 3)
9
int64
2
[12 34 23]
[12 23 37]
[34  2 23]
[23  2  3]
8
9


In [39]:
a = np.empty(6)
print(a)
b = np.ones([9,3])
print(b)
c = np.arange(1,11,2)
print(c)
d = np.linspace(1,11)
print(d)

[1. 1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[1 3 5 7 9]
[ 1.          1.20408163  1.40816327  1.6122449   1.81632653  2.02040816
  2.2244898   2.42857143  2.63265306  2.83673469  3.04081633  3.24489796
  3.44897959  3.65306122  3.85714286  4.06122449  4.26530612  4.46938776
  4.67346939  4.87755102  5.08163265  5.28571429  5.48979592  5.69387755
  5.89795918  6.10204082  6.30612245  6.51020408  6.71428571  6.91836735
  7.12244898  7.32653061  7.53061224  7.73469388  7.93877551  8.14285714
  8.34693878  8.55102041  8.75510204  8.95918367  9.16326531  9.36734694
  9.57142857  9.7755102   9.97959184 10.18367347 10.3877551  10.59183673
 10.79591837 11.        ]


In [56]:
a = np.array([23,12,9,342,232,23,1])
c = np.sort(a)
c

array([  1,   9,  12,  23,  23, 232, 342])

In [57]:
c

array([  1,   9,  12,  23,  23, 232, 342])

In [52]:
a = np.array([12,23,4532,12,675,1,212,1])
b = np.sort(a)
b

array([   1,    1,   12,   12,   23,  212,  675, 4532])

In [53]:
a

array([  12,   23, 4532,   12,  675,    1,  212,    1])

In [54]:
a = np.sort([23,1,12,23,98,67,5234,5346,10])
a

array([   1,   10,   12,   23,   23,   67,   98, 5234, 5346])

In [55]:
a

array([   1,   10,   12,   23,   23,   67,   98, 5234, 5346])

In [64]:
a + c # For adding two arrays element we can use + operator

array([ 24,  21,  21, 365, 255, 255, 343])

In [59]:
c + a

array([ 24,  21,  21, 365, 255, 255, 343])

In [61]:
s = np.array([9,8,7,6,5,4,3,2,1])
r = np.array([1,2,3,4,5,6,7,8,9])
s + r

array([10, 10, 10, 10, 10, 10, 10, 10, 10])

In [66]:
new = np.concatenate((s,r)) # For concatenating two arrays we can use concatenate method
new

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
a = np.array([[1,2],[4,5]])
b = np.array([[9,8],[6,5]])
print('a \n',a)
print('b \n',b)

a 
 [[1 2]
 [4 5]]
b 
 [[9 8]
 [6 5]]


In [68]:
n = np.concatenate((a,b),axis = 0)
n

array([[1, 2],
       [4, 5],
       [9, 8],
       [6, 5]])

In [73]:
x = np.concatenate((a,b),axis = 1)
x

array([[1, 2, 9, 8],
       [4, 5, 6, 5]])

In [ ]:
axis = 0
|
|
|
|
|
|
↓




axis = 1
-------------→

In [78]:
a = np.array([67,23,453,23,23])
b = np.array(0)
a * b

array([0, 0, 0, 0, 0])